// ------------------------------------------------------------------------------
// <auto-generated>
// Este código lo generó una herramienta.
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se regenera el código. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.UI.WebControls;

namespace PaginaWS
{
    public partial class SiteMaster
    {

        /// <summary>
    /// Control MainContent.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
        protected ContentPlaceHolder MainContent;
    }
}