// ------------------------------------------------------------------------------
// <auto-generated>
// Este código lo generó una herramienta.
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se regenera el código. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace PaginaWS
{
    public partial class Site_Mobile
    {

        /// <summary>
    /// Control Head1.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
        protected HtmlHead Head1;

        /// <summary>
    /// Control HeadContent.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
        protected ContentPlaceHolder HeadContent;

        /// <summary>
    /// control form1.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
        protected HtmlForm form1;

        /// <summary>
    /// Control FeaturedContent.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
        protected ContentPlaceHolder FeaturedContent;

        /// <summary>
    /// Control MainContent.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
        protected ContentPlaceHolder MainContent;

        /// <summary>
    /// Control ViewSwitcher1.
    /// </summary>
    /// <remarks>
    /// Campo generado automáticamente.
    /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    /// </remarks>
        protected UserControl ViewSwitcher1;
    }
}